# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# This file defines environment-specific targets used by the CRE CLI.
# Each top-level key is a target (e.g., `production`, `production-testnet`, etc.).
#
# You can define your own custom target names, such as `my-target`, and point
# the CLI to it via an environment variable.
#
# Below is an example `my-target`:
#
# my-target:
#   cre-cli:
#     # Required: Workflow DON ID used for registering and operating workflows.
#     don-family: "small"
#   logging:
#     # Optional: Path to the seth configuration file (TOML). Used for logging configuration.
#     seth-config-path: "/path/to/seth-config.toml"
#   rpcs:
#     # Required: Map each used chain selector to a corresponding RPC URL (HTTPS)
#     - chain-name: ethereum-mainnet
#       url: "https://sepolia.infura.io/v3/YOUR_API_KEY"

# ==========================================================================
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://por.bcy-p.metalhosts.com/cre-alpha/MvqtrdftrbxcP3ZgGBJb3bK5/ethereum/sepolia

# ==========================================================================
production-testnet:
  cre-cli:
    don-family: "zone-a"
  logging:
    seth-config-path: ""
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://sepolia.infura.io/v3/YOUR_API_KEY
    - chain-name: ethereum-testnet-sepolia-base-1
      url: <select your own rpc url>
